version: '3.9'

services:
  db:
    image: 'postgres'
    ports:
      - '4321:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - photoalbum-db:/var/lib/postgresql/data

  server:
    build: 
      context: .
    environment:
      DB_SCHEMA: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  photoalbum-db:

